platform :ios, '9.0'
target 'MovieApp' do
pod 'RestKit', '~> 0.27'
pod 'SDWebImage', '~> 3.8'
pod 'youtube-ios-player-helper', '~> 0.1’
pod 'Fabric'
pod 'Crashlytics'
pod 'KeychainItemWrapper'
pod 'FontAwesome-iOS'
pod ‘Realm’
pod ‘MWPhotoBrowser’
end